# https://taskfile.dev

## Specify the Taskfile format that this file conforms to.
version: '3'

# A set of task definitions.
tasks:
  default:
    desc: 'List all available tasks.'
    cmds:
      - task --list
    silent: true

  # ----- Docker commands -----
  start:
    desc: "Start docker container."
    cmds:
      - docker compose up -d
    silent: true

  stop:
    desc: "Stop docker container."
    cmds:
      - docker compose down -v
    silent: true
  
  # ----- Data Contract commands -----
  init-contract:
    desc: "Initialize a base data contract."
    cmds:
      - uv run datacontract init base.yaml
    silent: true
  
  lint-contract:
    desc: "Lint data contract."
    cmds:
      - uv run datacontract lint
    silent: true

  import-contract:
    desc: "Import data contract from SQL file."
    cmds:
      - uv run datacontract import --format sql --source ./init-scripts/create-tables.sql > import.yaml
    silent: true

  export-contract:
    desc: "Export data contract in jsonschema."
    cmds:
      - uv run datacontract export --format jsonschema --model futurama >> futurama_schema.json
    silent: true
  
  test-contract:
    desc: "Test data contract."
    cmds:
      - uv run datacontract test
    silent: true